---
title: "Run_model"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(cmdstanr, tidyverse,posterior, bayesplot, tidybayes,
               brms, patchwork, cowplot,ggpubr,flextable)


invisible(lapply(
  list.files(here::here("Experimental analysis", "Scripts"), full.names = TRUE),
  function(f) source(f, echo = FALSE, print.eval = FALSE)
))

```
## Extracting the data:

```{r, warning=F, message=F}
df = load_data()
```



## plotting the behavioral data:
```{r, fig.height=6,fig.width=8, message=F,warning=F}
plot_beh_data(df,NULL,F)
```

## fit the standard model with meta-uncertainty and meta-bias
```{r}
model1 = cmdstanr::cmdstan_model(here::here("Stanmodels","Heurestic models","Emperical dataanalysis","Single Subject","model1.stan"))

dd = df %>% 
  mutate(subject = as.numeric(as.factor(subject))) %>% 
  filter(Trialtype == "Main", scale == "conf") %>% drop_na()

dd_by_subj <- split(dd, dd$subject)

fits <- lapply(dd_by_subj, function(d) {
  fit_model_ss(d, model1, 500)
})

models = list.files(here::here("Experimental analysis","Heurestic models","saved models"), full.names = T)

fits = list()
for(model in models[1:8]){
  fit = readRDS(model)
  fits[[str_remove(str_remove(str_split(model, "/")[[1]][9],".rds"),"fit_")]] = fit  
}

```


```{r, fig.width=8,fig.height=6}
dia(fits, dd)
```

## load the models
```{r}
name = "kelly"
fit1 <- readRDS(here::here("Savedmodels",paste0("fit1_",name,".rds")))
fit2 <- readRDS(here::here("Savedmodels",paste0("fit2_",name,".rds")))
fit3 <- readRDS(here::here("Savedmodels",paste0("fit3_",name,".rds")))
```


## compare models on approximate LOO
```{r}
loom1 = fit1$loo()
loom2 = fit2$loo()
loom3 = fit3$loo()
loo::loo_compare(list(loom1,loom2,loom3))
```


## Getting model predictions
```{r}
predictions = get_model_predictions_model_1(fit1)
```


## ploting the results
```{r,fig.height=8,fig.width=12}
plots = Plot_group_predictive_psycho(predictions,df,ACC = F,n_bins = 15)
# jespere = plots[[1]]
jespere
# kelly = plots[[1]]
kelly

# siebe

```

## marginal posterior estimates of parameters
```{r,fig.height=8,fig.width=12}
get_marginal_estimates(fit1)[[2]]
get_marginal_estimates(fit2)[[2]]
get_marginal_estimates(fit3)[[2]]

rbind(get_marginal_estimates(fit1)[[1]] %>% mutate(model = "1"),
      get_marginal_estimates(fit2)[[1]]%>% mutate(model = "2"),
      get_marginal_estimates(fit3)[[1]]%>% mutate(model = "3")
) %>%  
  filter(name %in% c("meta_un_int","meta_un_beta","meta_bias_int","meta_bias_beta","rho_p_conf")) %>% 
  ggplot(aes(x = value, fill = as.factor(model)))+
    geom_histogram(col = "black", position = "identity", alpha = 0.5)+
    facet_wrap(~name, scales = "free", nrow = 1)+
    scale_y_continuous(breaks = scales::pretty_breaks(n = 3))+
    scale_x_continuous(breaks = scales::pretty_breaks(n = 3))+
    theme_classic(base_size = 14)+
  theme(legend.position = "top")
  
```


