---
title: "Fit_MCMC_simu"
author: ""
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    number_sections: true
    theme: flatly
    highlight: tango
    code_folding: hide
    df_print: paged
---

```{r}
pacman::p_load(tidyverse,posterior,bayesplot,cmdstanr,patchwork,ordbetareg,shiny,statConfR)
source(here::here("Simulations","MCMC","simulate.R"))
```


```{r, fig.height=12,fig.width=8}
df = simulate_data()
p1 = df %>% ggplot(aes(x = X*D, y = a_gauss))+geom_point()
p2 = df %>% ggplot(aes(x = X*D, y = C, col = as.factor(ACC)))+geom_point()+geom_smooth()
p1/p2
```


```{r, fig.height=12,fig.width=8}
fit = function(nn){
  
  qq = rnorm(1,1,1)
  
  df = simulate_data(n = nn)
  
  mod = cmdstanr::cmdstan_model(here::here("Simulations","MCMC","stanmodels","MCMC_sim.stan"))

  datastan = list(a = df$a_gauss,
                D = df$D,
                C = df$C,
                N = nrow(df),
                X = df$X)


  fit = mod$sample(data = datastan,
                   iter_warmup = 500,
                   refresh = 0,
                   iter_sampling = 500,
             parallel_chains = 4)
  
  div = data.frame(fit$diagnostic_summary())%>% mutate(sim = qq, trial = nn,
                                                      time = fit$time()$total)
  
    
  esti_real = fit$summary(c("lp__","sigma_choice","sigma_m","sigma_e","mean_choice","prec_conf","c0","c1")) %>% 
    mutate(simulated = c(NA,unique(df$sigma_k),unique(df$sigma_m),unique(df$sigma_e),
                         unique(df$mean_choice),unique(df$conf_prec),unique(df$c0),unique(df$c1))) %>% 
    mutate(div = max(div$num_divergent))

  
  data = df %>% mutate(conf_bin = cut(C,4),
                      stimulus  = as.factor(D),
                      participant = 1,
                      rating = as.numeric(as.factor(conf_bin)),
                      correct = ACC) %>% drop_na()


  
  mratio = fitMetaDprime(data)
  
    
  result = list(esti_real%>% mutate(sim = qq, trial = nn),
                df%>% mutate(sim = qq, trial = nn),
                div = div,
                mratio = mratio %>% mutate(sim = qq, trial = nn))
  
  return(result)
}

# qq = fit(nn = 200)


library(furrr)
library(purrr)
library(tidyverse)

plan(multisession, workers = 2)  # Windows-friendly

safe_function <- possibly(fit, otherwise = "Error")

# Run 20 times in parallel
results_list <- future_map(1:10, ~ safe_function(200), .progress = T)

saveRDS(results_list,here::here("1500_no_metabias_phi_thight_rdm_metad.RData"))

results_list = results_list[-which(results_list == "Error")]
```

```{r}
inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,3) %>% select(mean,variable,sim) %>% pivot_wider(names_from = "variable",values_from = "mean") %>% 
    unnest() %>% rename(esti_conf_prec = conf_prec)
) %>% 
  ggplot(aes(x = beta, y = 1/sqrt(sigma_k^2+sigma_e^2)))+geom_point()+geom_abline()


inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,3) %>% select(mean,variable,sim) %>% pivot_wider(names_from = "variable",values_from = "mean") %>% 
    unnest() %>% rename(esti_conf_prec = conf_prec)
) %>% 
  ggplot(aes(x = meta_un_cor, y = 1/sqrt(sigma_m^2+sigma_e^2)))+geom_point()+geom_abline()



inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,3) %>% select(mean,variable,sim) %>% pivot_wider(names_from = "variable",values_from = "mean") %>% 
    unnest() %>% rename(esti_conf_prec = conf_prec)
) %>% 
  ggplot(aes(x = esti_conf_prec, y = conf_prec))+geom_point()+geom_abline()



inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,3) %>% select(mean,variable,sim) %>% pivot_wider(names_from = "variable",values_from = "mean") %>% 
    unnest() %>% rename(esti_conf_prec = conf_prec)
) %>% 
  ggplot(aes(x = meta_un_inc, y = sigma_m+sigma_e))+geom_point()+geom_abline()


inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,3) %>% select(mean,variable,sim) %>% pivot_wider(names_from = "variable",values_from = "mean") %>% 
    unnest() %>% rename(esti_conf_prec = conf_prec)
) %>% 
  ggplot(aes(x = meta_un_inc, y = sigma_k))+geom_point()+geom_abline()



```


```{r}

divs = map_dfr(results_list,6) %>% group_by(sim) %>% 
  summarise(mean_div = mean(num_divergent),
            mean_tree = mean(num_max_treedepth)) 

inner_join(inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,7) %>% select(mean,variable,sim) %>% pivot_wider(names_from = "variable",values_from = "mean") %>% 
    unnest() %>% rename(esti_conf_prec = prec_conf,
                        esti_sigma_k = sigma_choice,
                        esti_sigma_m = sigma_m,
                        esti_sigma_e = sigma_e,
                        esti_c0 = c0,
                        esti_c1 = c1)
),
divs) %>% filter(mean_div == 0 & mean_tree == 0) %>% 
  ggplot(aes(x = sigma_m, y = esti_sigma_m))+geom_point()+geom_abline()



inner_join(inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,7) %>% select(mean,variable,sim) %>% pivot_wider(names_from = "variable",values_from = "mean") %>% 
    unnest() %>% rename(esti_conf_prec = prec_conf,
                        esti_sigma_k = sigma_choice,
                        esti_sigma_m = sigma_m,
                        esti_sigma_e = sigma_e,
                        esti_c0 = c0,
                        esti_c1 = c1)
),
divs) %>% filter(mean_div == 0 & mean_tree == 0) %>%  
  ggplot(aes(x = sigma_e, y = esti_sigma_e))+geom_point()+geom_abline()



inner_join(inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,7) %>% select(mean,variable,sim) %>% pivot_wider(names_from = "variable",values_from = "mean") %>% 
    unnest() %>% rename(esti_conf_prec = prec_conf,
                        esti_sigma_k = sigma_choice,
                        esti_sigma_m = sigma_m,
                        esti_sigma_e = sigma_e,
                        esti_c0 = c0,
                        esti_c1 = c1)
),
divs) %>% filter(mean_div == 0 & mean_tree == 0) %>% 
  ggplot(aes(x = sigma_k, y = esti_sigma_k))+geom_point()+geom_abline()


```



```{r}
inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,8)
) %>% 
  ggplot(aes(x = 1/sqrt(sigma_k^2+sigma_e^2), y = dprime))+geom_point()+geom_abline()

inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,8)
) %>% 
  ggplot(aes(x = sigma_m, y = metaD, col = sigma_k))+geom_point()

inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,8)
) %>% 
  ggplot(aes(x = sigma_e, y = metaD))+geom_point()


inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,8)
) %>% 
  ggplot(aes(x = 1/sqrt(sigma_m^2+sigma_e^2), y = metaD))+geom_point()+geom_abline()



inner_join(
  map_dfr(results_list,1), 
  map_dfr(results_list,8)
) %>% mutate(sigma_k_bin = cut(sigma_k,10)) %>% 
  filter((1/sqrt(sigma_m^2+sigma_e^2-sigma_k^2)) < 3) %>% 
  ggplot(aes(x = log((1/sqrt(sigma_m^2+sigma_e^2+sigma_k^2))), y = metaD-2, col = sigma_k_bin))+
  geom_point()+
  # facet_wrap(~sigma_k_bin)+
  geom_abline()



```


## fit hierarchical version

```{r}
df4 <- read_csv(here::here("Data","Pilots","Kelly_2025_17_12","RDM_reportz_sub3_1.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
  # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  filter(RT < 2.5) %>% 
  mutate(Confidence = (SR_conf+1)/2) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  mutate(Subject = 4)



df3 <- read_csv(here::here("Data","Pilots","Jesper_2025_17_12","RDM_reportz_sub5.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
    mutate(Confidence = (SR_conf+1)/2) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  mutate(Subject = 3) 


df2 <- read_csv(here::here("Data","Pilots","Siebe_2025_03_12","data.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2) %>% 
  filter(RT < 2.5) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  mutate(Subject = 2) %>% 
  drop_na()


df1 <- read_csv(here::here("Data","Pilots","Siebe_2025_17_12","RDM_reportz_sub6.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2)  %>% 
  filter(RT < 2.5) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  mutate(Subject = 1) %>% 
  drop_na()


dd = rbind(df1,df2,df3,df4)


mod = cmdstanr::cmdstan_model(here::here("Derivations","Hierarchical","nort.stan"))


datastan = list(a = dd$Y,
                D = dd$D,
                C = dd$Confidence,
                N = nrow(dd),
                X = dd$coherence,
                S = length(unique(dd$Subject)),
                S_id = dd$Subject)


fit = mod$sample(data = datastan,
                 iter_warmup = 500,
                 refresh = 100,
                 adapt_delta = 0.95,
                 max_treedepth = 12,
                 iter_sampling = 500,
           parallel_chains = 4)

fit$save_object(here::here("Savedmodels","removed_models","fit1_hier_mec.rds"))


parameters = c("gm","tau_u")
sum = fit$summary(c(parameters))

plot = mcmc_pairs(fit$draws(c(parameters)),np = nuts_params(fit))
plot2 = mcmc_trace(fit$draws(c(parameters)),np = nuts_params(fit))
```