---
title: "Decision and Confidence: Evidence-Based Policy with Metacognition"
author: ""
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    number_sections: true
    theme: flatly
    highlight: tango
    code_folding: hide
    df_print: paged
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(cmdstanr, tidyverse,posterior, bayesplot, tidybayes,
               brms, patchwork, cowplot,ggpubr,flextable)


invisible(lapply(
  list.files(here::here("Experimental analysis", "Scripts"), full.names = TRUE),
  function(f) source(f, echo = FALSE, print.eval = FALSE)
))

```
## Extracting the data:

```{r, warning=F, message=F}
df = load_data()
```   

## plotting the behavioral data:
```{r, fig.height=6,fig.width=8, message=F,warning=F}
plot_beh_data(df,NULL,F)
```


## fit the standard model with meta-uncertainty and meta-bias
```{r}
model1 = cmdstanr::cmdstan_model(here::here("Stanmodels","CANSANDRE","Emperical dataanalysis","Single Subject","CASANDRE.stan"))

dd = df %>% 
  mutate(subject = as.numeric(as.factor(subject))) %>% 
  filter(Trialtype == "Main", scale == "conf") %>% drop_na()

dd_by_subj <- split(dd, dd$subject)

fits <- lapply(dd_by_subj, function(d) {
  fit_model_ss(d, model1, 500)
})

```




```{r, fig.width=8,fig.height=6}
dia(fit_kelly)
```


```{r, fig.width=8,fig.height=6}
dia(fit_jesper)
```


```{r, fig.width=8,fig.height=6}
dia(fit_siebe)
```



```{r, fig.width=8,fig.height=6}
dia(fit_siebe2)
```
