---
title: "Models and Data In Perceptual Decision Making"
output: html_document
---


There has been several approaches at determining whether and how post decisional evidence accumulation (PDEA) works [@DESENDERUnderstandingNeuralSignalsPostdecisionalPerformanceMonitoring2021]. One line of studies examine PDEA using mouse or eye-tracking, in order to continously track the decision making process. Using mouse tracking and intercrainal recordings in patents suffering from epilepsy [@GOUEYTESEvidenceAccumulationPresupplementaryMotorAreaInsula2025] examined which anatomial regions of the brain serve as correlates of evidence accumulation, confidence and changes of mind. Results showed that the pre-supplementary motor area generally were associated with confidence, change of mind and evidence accumulation whereas the insula were more inline with post decisional evidence accumulation.  Most importantly for our discussion it was found that the average post decisional confidence time was $0.3 \pm 0.09s$ indicating a very fast process that unlikely is influenced by much conscious control. 

In a similar study in health individuals [@RESULAJChangesMindDecisionmaking2009] showed similar behavioral results, where aggregated (across change of mind and usual decision making) response times in a similar task were around 0.5s. Interestingly when reexamining Figure 2 in their paper there seems to be a slight interaction effect between the difficultly of the trial (i.e. stimulus intensity) and whether the change of mind was beneficial for accuracy, i.e. for hard trials (very low coherence in the Random Dot Motion task), changes of mind seemed to do nothing or perhaps even be detrimental, whereas for easier trials (high coherence) changes of mind were on averaged observed to be beneficial for accuracy. 

In a seminal paper [@KIANIRepresentationConfidenceAssociatedDecisionNeuronsParietal2009] showed how in Rhesus monkeys how a single anatomical region was both related to the formation of a choice and the confidence in that choice. These studies dynamically investigate the decision making and confidence formation process and generally suggest a PDEA window that might be small enough to be outside much of conscious intervention. Furthermore, the neural recordings generally show that similar areas are associated with evidence accumulation and confidence and or changes of mind, with the insula particularly mentioned for PDEA. Next we turn to experimental studies that investigate PDEA by either letting participants accumulate additional evidence after the initial decision has been made, or by manipulating the time between choice and confidence rating. 


Firstly, [@FLEMINGNeuralMediatorsChangesMindPerceptualDecisions2018a] showed over two experiments (one with fMRI) how providing additional viewing time of the stimulus after the binary choice was made can increase the efficiency of the confidence ratings (i.e. how well they can distinguish between correct and incorrect choices). This was done in a experimental paradigm where the stimulus was presented for only 300m then a choice was made and then after 300ms of additional stimuli presentation. In a series of studies [@YUDynamicsPostdecisionalProcessingConfidence2015] investigated how increasing the time between binary choices and confidence ratings influenced confidence ratings in correct and incorrect choices. 


Here we also want to highlight a particular assumption and or logical flow that is generally followed in the two ways of describing both choice and confidence formation. Dynamic models of choice generally follow a principle of mechanistic parsimony, positing that decision formation and performance monitoring rely on the same accumulation mechanism, although alternative and or distinct mechanisms remain plausible.
 
Another way to investigate PDEA is to instruct subjects to either be as fast or as accurate as possible. [@BARANSKIProbingLocusConfidenceJudgmentsExperimentsTime1998] showed in a series of well designed experiments how such instructions change the temporal dynamics of binary responses and confidence judgements. Findings from these experiments showed that under speed stress (i.e. reporting as fast as possible, below 500ms), confidence response times increased, whereas under accuracy stress (i.e. reporting as accurately as possible) indicating that PDEA was happening. However, under accuracy stress no such association was found. Furthermore, as was also found in [@RESULAJChangesMindDecisionmaking2009] there seemed to be an interaction between difficulty confidence and correctness in the speed stress condition. This pattern generally showed that for easy trials a response of "guessing" (the lowest confidence anchor) subjects were significantly below 50% accuracy with the easiest trials having accuracies around 10% and then a monotonic increase to 30% at the highest difficulty. As the confidence in the choice increased this relationship was flipped such that for "certain" confidence ratings the proportion of correct responses were around 100% for the easiest trials and monotonically decreasing for increasing difficultly down to around 80%. These findings and the authors suggests that under time-pressure choice evidence accumulation and PDEA can be disentangled as here computational resources are stressed in the sequential way of the task. However, under accuracy stress when the computational resources are not stressed the evidence accumulation for the choice and the confidence judgement seem to coincide. As a side effect of speed stress subjects seemed to have more error-monitoring (although the use of the half-scale). We believe that this finding can be explained by the fact that the speed stress condition introduces more motor-errors which are recognized and thus capitalized on. 

Now lastly the authors highlight an important prediction of the above suggestions, if participants are not instructed or instructed to give as accurate binary responses as possible then the introduction of a confidence rating should in principle increase the response time to the initial decision, compared to a case where only binary choices are collected. This has no later been confirmed by several different studies and groups [@PETRUSICJudgingConfidenceInfluencesDecisionProcessingComparative2003; @BARANSKITestingArchitecturesDecisionconfidenceRelation2001] (REFS).

[@TSETSOSActionPlanningTimescaleEvidenceAccumulation2015] used an interrogation task to probe the time course of evidence accumulation. Such interrogation tasks have a fixed time that the subject can view the stimulus (i.e. 150, 250, 350 .. ms (VT)) and are prompted to give a response as fast as possible after indication that the time interval has passed. Then by simultaneously manipulating the time between the initial binary choice and the confidence judgement (ITI) they investigated PDA. In their first study they showed that increasing ITI slightly decreased confidence ratings, however this was conditional on accuracy with confidence ratings for incorrect trials generally decreasing and for correct trials staying relatively stable, especially for easier trials. No test of the interaction between VT and ITI on confidence ratings were reported. 

In their second study they used a full-confidence scale, a RDM stimulus, 5 stimulus intensities and two conditions. The first condition subjects had access to the stimulus in the ITI whereas in the second they had not. Crucially the subjects had a fixed VT of 800ms. The main finding of experiment one was replicated now with even stronger effects (due to the use of more stimulus intensities and a full confidence scale), where confidence ratings for incorrect trials decreased significantly especially for easy trials, whereas correct trials remained relatively stable or slightly decreasing. Now crucially, whether the subject had access to the stimulus in the ITI did not cause any change in these relationships. 

Now lastly, because most of the above studies made use of the RDM task and suggest a pattern where PDEA is dependent on the time a subject is exposed to the stimulus, investigating the time needed to make as accuracte as possible judgements in this task could be helpful to determine not only when one would expect subject to have accumulated enough evidence for their inital choice, and thus give a hint to the temporal dynamics in this task. [@TSETSOSActionPlanningTimescaleEvidenceAccumulation2015] showed that subjects did not improve in the RDM task when stimulus presentation time was above 300-600ms. Further, they manipulated the stimulus-response mapping from trial to trial (i.e. respond left to indicate "up"), such that in some trials participants new before viewing the stimulus which key was associated with which direction and in other trials they only knew after viewing the stimulus. This manipulation did not significant change the length of the stimulus presentation time on accuracy. These results indicate that in order to make an optimal decision the participants needed to view the stimulus for short period of time and this did not change even when manipulating the stimulus-response mapping.


Taken together these above findings suggest a clear pattern for the circumstances in which PDEA might play a role in meta-cognition and error-monitoring. 

Firstly, PDEA unfolds within a very short temporal window. Both intracranial recordings and behavioral change-of-mind paradigms suggest that post-choice dynamics occur within a few hundred milliseconds ( ~300–500 ms). This time course suggest that PDEA is not driven by slow, deliberative, consciously controlled processes, but instead an  extension of the same evidence accumulation dynamics that gave rise to the initial choice.

Secondly, PDEA appears to be conditional on task demands and resource constraints. Under speed stress, choice and confidence can be partially dissociated, such that confidence response times increase, and for easy trials confidence ratings can better dissociate between correct and incorrect choices (particularly easy trials that are incorrect are recognized). In contrast, under accuracy stress, where sufficient time and computational resources are available, choice formation and confidence judgments appear to rely on largely overlapping evidence from the initial choice. This pattern supports the idea that PDEA becomes particularly visible when the primary decision process is pressed for time leaving potential time for PDEA because if not pressed evidence accumulation for both choice and confidence seem very close temporally if not completely overlapping. Importantly, in some paradigms PDEA does not depend on continued access to external sensory evidence, suggesting that internal evidence or residual neural activity may be sufficient to drive post-decisional updating. An alternative explanation 

Thirdly, given a short stimulus presentation (300-600ms) subjects quickly asymptotes in their performance, meaning that with increasing viewing time they do not perform better. This together with the fact that subjects generally respond much slower when they know that they have to give a confidence judgement compared to when they only have to give a binary choice, suggest that maybe subjects do most, if not all, of the processing of confidence pre-decisionally if allowed by the task demands. 


In sum, PDEA seems to operate within a narrow temporal window following choice commitment, and if subjects are stressed to produce a fast choice this PDEA can increase the ratings informativeness of choice accuracy. If one follows the argument of mechanistic parsimony, these results are well explained within an evidence accumulation framework of PDEA. However, we believe that there is a more generally parsimonious explanation of these data. 

The short time-window of PDEA seem to suggest that the post-decision computation is a relatively automatic process that at least somewhat coincides in the pre-supplementary motor area. Furthermore, under speed stress subjects produce more errors, we believe that these errors are partly due to a decreased time for coordination between the CNS and the effector. This reduced coordination makes it more likely that the subject produces a motor error, which will quickly be picked up subject and then a low (even below guessing) confidence rating can be elicited. The process of an agent producing a motor error and subsequently becoming aware of it is consistent with motor control theory, particularly comparator models involving efference copy mechanisms. In this framework the evidence for the intial choice could be formed by an evidence accumulation, but then when enough evidence has been accumulated the agent acts, this action produces an efferent signal to the target muscles that produce the action. Meanwhile in the Central nervous system a copy of this signal (the efference copy) is processed by an internal prediction system that uses a forward model to compute / predict the expected consequences and subsequent afferent signals. As the action is executed and the afferent signals gets processed in the central nervous system, the brain compares these afferent signals with the predictions from the forward model in a comparator mechanism that then generates a short of prediction error. In short, the brain generates a signal to the periphery and then asks the question, "did i get the sensory feedback that i expected given the command that i sent". This theory would therefore predict that having generated the efference copy, with or without the efferent signal, a subject would be able judge its confidence, but only conditional on the action being what was expected. Then with the information about the agents own action, it is possible for the agent to change its mind on whether they believe it to be correct or not.


We propose that Error-monitoring, at least partly, arises from variability in the choice process itself. Here contrary to most models of perceptual decision making that assume a deterministic choice after the evidence has been acquired, we propose that agents can be aware that they erred if instead of a deterministic process choices are generated through a stochastic process. Said another way we assume that there exists choice variability.

Usually in perceptual decision making models evidence variability and choice variability would be indistinguishable when observing only binary responses. 
However, by incorporating confidence ratings, we can disentangle these noise sources.
We demonstrate that our model, which includes choice variability, can produce most of the above described patterns of confidence ratings and choices and represents a specific instantiation of Fleming and Daw's second-order framework without the need for independent information for the generation of confidence ratings to have error monitoring.
