---
title: "Run_model"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(cmdstanr, tidyverse,posterior, bayesplot, tidybayes,
               brms, patchwork, cowplot,ggpubr,flextable)


source(here::here("Sequential sampling", "utility.R"))

```

## Extracting the data:

```{r, warning=F, message=F}
df = load_data()
```


## plotting the behavioral data:

```{r, fig.height=6,fig.width=8, message=F,warning=F}
plots = plot_beh_data(df%>% filter(Trialtype == "SC dotlife"), 7, F)

plots
```


```{r, fig.height=6,fig.width=8, message=F,warning=F}
plots = plot_beh_data(df%>% filter(Trialtype == "SC coherence"), 7, F)

plots
```

```{r, fig.height=6,fig.width=8, message=F,warning=F}
plots = plot_beh_data(df%>% filter(Trialtype == "Main", scale == "conf"), 7, F)

plots
```


## check subjects for exclusion and  fit the subject level model for each subject:

```{r}
dd = df %>% 
  mutate(subject = as.numeric(as.factor(subject))) %>% 
  filter(Trialtype == "Main", scale == "conf") %>% 
    filter(
  abs(X) < case_when(
    ID == "RDM_reportz_sub001.csv" ~ 0.6,
    ID == "RDM_reportz_sub010.csv" ~ 0.4,
    TRUE ~ Inf
  )) %>% 
  group_by(subject) %>% 
  mutate(
    trial_n = 1:n(), n_trials = n()
  ) %>% 
  ungroup() %>% 
  mutate(
    across(-c("ID","subject"),
      ~ ifelse(
        ID == "RDM_reportz_sub030.csv" & trial_n > (n_trials - 36),
        NA,
        .
      )
    )
  ) 


exclusions_correct = dd %>% group_by(ID) %>% summarize(n = sum(Correct)/n()) %>% filter(n < 0.60)

exclusions_ntrials = dd %>% 
  select(interTrial.interval, interval,coherence,X,Correct,Y,RT,Confidence,ID) %>% 
    mutate(
    no_response = is.na(Correct) |
                  is.na(Confidence) |
                  is.na(RT) |
                  RT < 0.150) %>% 
  group_by(ID) %>%
  summarize(noresp_rate = mean(no_response)) %>%
  filter(noresp_rate > 0.3)

n_excluded_correctness = length(unique(exclusions_correct$ID))
n_excluded_trials = length(unique(exclusions_ntrials$ID))

n_excluded = length(unique(c(exclusions_correct$ID, exclusions_ntrials$ID)))

dd = dd %>% filter(!ID %in% c(exclusions_correct$ID, exclusions_ntrials$ID)) %>% drop_na()

dd_by_subj <- split(dd, dd$ID)
```


```{r, message=F, error=F, warning=F}
plots = plot_beh_data(dd, 12, F)

plots

```



```{r}
if(length(list.files(here::here("Sequential sampling","Fits","Single Subject"))) == length(dd_by_subj)){
  
  models = list.files(here::here("Sequential sampling","Fits","Single Subject"), full.names = T)
  fits = list()
  for(model in models[1:length(models)]){
    fit = readRDS(model)
    paths = str_split(model, "/")[[1]]
    name = paths[length(paths)]
    
    fits[[str_remove(str_remove(name,".rds"),"fit_")]] = fit  
  }
  
}else{
  fits <- lapply(dd_by_subj, function(d) {
  fit_model_ss(d)})
}
```


```{r}
if(length(list.files(here::here("Sequential sampling","Fits","Single Subject nolapse"))) == length(dd_by_subj)){
  
  models = list.files(here::here("Sequential sampling","Fits","Single Subject nolapse"), full.names = T)
  fits = list()
  for(model in models[1:length(models)]){
    fit = readRDS(model)
    paths = str_split(model, "/")[[1]]
    name = paths[length(paths)]
    
    fits[[str_remove(str_remove(name,".rds"),"fit_")]] = fit  
  }
  
}else{
  fits <- lapply(dd_by_subj, function(d) {
  fit_model_ss_nolapse(d)})
}


```





```{r, fig.width=8,fig.height=6}
diagnoistics_ss = dia(fits, dd)

diagnoistics_ss[[1]]


map_dfr(diagnoistics_ss,4)
```


## Fit Hierarchical model

```{r}
if(file.exists(here::here("Sequential sampling","Fits","Hierarchical","Hierarchical.rds"))){
    model = list.files(here::here("Sequential sampling","Fits","Hierarchical"), full.names = T)
    fit = readRDS(model[grepl("Hierarchical.rds",model)])
}else{
  fit = fit_model_hier(dd)
}
```

```{r, fig.width=16,fig.height=12}
hierarchical_diagnostics = dia_hier(fit, dd,lapse = T)
hierarchical_diagnostics
```

```{r}
if(file.exists(here::here("Sequential sampling","Fits","Hierarchical","Hierarchical_nolapse.rds"))){
    model = list.files(here::here("Sequential sampling","Fits","Hierarchical"), full.names = T)
    fit = readRDS(model[grepl("Hierarchical_nolapse.rds",model)])
}else{
  fit = fit_model_hier_nolapse(dd)
}
```


```{r, fig.width=16,fig.height=12}
fit <- readRDS(here::here("~/RDM-metacognition/Sequential sampling/Fits/allmodels/Hierarchical_nolapse_50_clamped_standard.rds"))

hierarchical_diagnostics = dia_hier(fit, dd,lapse = F)
hierarchical_diagnostics
```

# bayes factors:

```{r}
bf_sigmam = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[7]")) %>% .$`gm[7]`),prior = rnorm(4000,0,0.5))
bf_metabias = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[8]")) %>% .$`gm[8]`),prior = rnorm(4000,0,0.5))

Bayesfactor_data = data.frame(BF = bf_sigmam, subjects = length(dd_by_subj))

hierarchical_diagnostics_saved = list(hierarchical_diagnostics[[1]],hierarchical_diagnostics[[4]],hierarchical_diagnostics[[6]])

Seq_samp = list(n_excluded_correctness,n_excluded_trials,n_excluded,hierarchical_diagnostics_saved,Bayesfactor_data)

saveRDS(Seq_samp, here::here("Preregistration","Results","SS",paste0("SS_",length(dd_by_subj),".rds")))

```


# posterior predictives:

```{r, fig.width=8,fig.height=6, error=F,message=F,warning=F}
pps_bin10 = pp_hier_nolapse(fit, dd, n_bins = 10)
pps_mobin = pp_hier_nolapse(fit, dd, n_bins = NULL)

pps_bin10[[1]]
pps_bin10[[3]]
pps_mobin[[1]]
pps_mobin[[3]]

pps = pps_mobin

ggsave(here::here("Sequential sampling" , "figures","group_level_pred.png"),pps_bin10[[3]], dpi = 300, width = 8, height = 6)
```

# posterior predictives for centered beta

```{r, fig.width=8,fig.height=6, error=F,message=F,warning=F}
# pps_bin10 = pp_hier_nolapse_centbeta(fit, dd, n_bins = 10)
# pps_mobin = pp_hier_nolapse_centbeta(fit, dd, n_bins = NULL)

# pps_bin10[[1]]
# pps_bin10[[3]]
# pps_mobin[[1]]
# pps_mobin[[3]]
# 
# pps = pps_mobin

# ggsave(here::here("Sequential sampling" , "figures","group_level_pred.png"),pps_bin10[[3]], dpi = 300, width = 8, height = 6)
```


```{r, fig.width=8,fig.height=6, error=F,message=F,warning=F}
pps[[2]]
```


```{r,fig.height=11, fig.width=18, warning=F, }
library(ggplot2)
library(patchwork)

# Arrange in a 2-row × 4-column grid, collect all legends
combined_plot <- wrap_plots(pps[[2]][1:9], ncol = 3, nrow = 3, guides = "collect", axis_titles = "collect")

combined_plot = combined_plot+theme(axis.title = element_text(size = 14),
                       axis.text = element_text(size = 12, color = "black"),
                       axis.ticks.length = unit(0.2, "cm"))


combined_plot2 <- wrap_plots(pps[[2]][10:18], ncol = 3, nrow = 3, guides = "collect", axis_titles = "collect")

combined_plot2 = combined_plot2+theme(axis.title = element_text(size = 14),
                       axis.text = element_text(size = 12, color = "black"),
                       axis.ticks.length = unit(0.2, "cm"))

combined_plot3 <- wrap_plots(pps[[2]][19:27], ncol = 3, nrow = 3, guides = "collect", axis_titles = "collect")

combined_plot3 = combined_plot3+theme(axis.title = element_text(size = 14),
                       axis.text = element_text(size = 12, color = "black"),
                       axis.ticks.length = unit(0.2, "cm"))


combined_plot4 <- wrap_plots(pps[[2]][28:36], ncol = 3, nrow = 3, guides = "collect", axis_titles = "collect")

combined_plot4 = combined_plot4+theme(axis.title = element_text(size = 14),
                       axis.text = element_text(size = 12, color = "black"),
                       axis.ticks.length = unit(0.2, "cm"))

combined_plot5 <- wrap_plots(pps[[2]][37:45], ncol = 3, nrow = 3, guides = "collect", axis_titles = "collect")

combined_plot5 = combined_plot5+theme(axis.title = element_text(size = 14),
                       axis.text = element_text(size = 12, color = "black"),
                       axis.ticks.length = unit(0.2, "cm"))

combined_plot6 <- wrap_plots(pps[[2]][46:50], ncol = 3, nrow = 3, guides = "collect", axis_titles = "collect")

combined_plot6 = combined_plot6+theme(axis.title = element_text(size = 14),
                       axis.text = element_text(size = 12, color = "black"),
                       axis.ticks.length = unit(0.2, "cm"))


combined_plot
combined_plot2
combined_plot3
combined_plot4
combined_plot5
combined_plot6

ggsave(here::here("Sequential sampling" , "figures","subj1_pred.png"),combined_plot, dpi = 300, width = 12, height = 12)
ggsave(here::here("Sequential sampling" , "figures","subj2_pred.png"),combined_plot2, dpi = 300, width = 12, height = 12)
ggsave(here::here("Sequential sampling" , "figures","subj3_pred.png"),combined_plot3, dpi = 300, width = 12, height = 12)
ggsave(here::here("Sequential sampling" , "figures","subj4_pred.png"),combined_plot4, dpi = 300, width = 12, height = 12)
ggsave(here::here("Sequential sampling" , "figures","subj5_pred.png"),combined_plot5, dpi = 300, width = 12, height = 12)
ggsave(here::here("Sequential sampling" , "figures","subj6_pred.png"),combined_plot6, dpi = 300, width = 12, height = 12)

```






```{r,fig.height=12, fig.width=18}
models = list.files(here::here("Sequential sampling","Fits","allmodels"), full.names = T)

df  = data.frame()

for (model in models){
  print(model)
  fit = readRDS(model)

  type = str_extract(model, "standard|narrow|super_narrow|superduper_narrow|wide")
  subs = str_extract(model, "(?<=nolapse_)\\d+")
  
  if(type == "standard"){
    bf_sigmam = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[7]")) %>% .$`gm[7]`),prior = rnorm(4000,0,0.5))
    bf_metabias = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[8]")) %>% .$`gm[8]`),prior = rnorm(4000,0,0.5))
    
    Bayesfactor_data = data.frame(variable = c("sigmam_beta","metabias_beta"),BF = c(bf_sigmam,bf_metabias), subs = subs)

  }else if(type == "narrow"){
    bf_sigmam = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[7]")) %>% .$`gm[7]`),prior = rnorm(4000,0,0.25))
    bf_metabias = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[8]")) %>% .$`gm[8]`),prior = rnorm(4000,0,0.25))
    
    Bayesfactor_data = data.frame(variable = c("sigmam_beta","metabias_beta"),BF = c(bf_sigmam,bf_metabias), subs = subs)

  }else if(type == "super_narrow"){
    bf_sigmam = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[7]")) %>% .$`gm[7]`),prior = rnorm(4000,0,0.05))
    bf_metabias = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[8]")) %>% .$`gm[8]`),prior = rnorm(4000,0,0.05))
    
    Bayesfactor_data = data.frame(variable = c("sigmam_beta","metabias_beta"),BF = c(bf_sigmam,bf_metabias), subs = subs)

  }else if(type == "superduper_narrow"){
    bf_sigmam = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[7]")) %>% .$`gm[7]`),prior = rnorm(4000,0,0.01))
    bf_metabias = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[8]")) %>% .$`gm[8]`),prior = rnorm(4000,0,0.01))
    
    Bayesfactor_data = data.frame(variable = c("sigmam_beta","metabias_beta"),BF = c(bf_sigmam,bf_metabias), subs = subs)

  }else if(type == "wide"){
    bf_sigmam = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[7]")) %>% .$`gm[7]`),prior = rnorm(4000,0,1))
    bf_metabias = get_bf(post = as.numeric(as_draws_df(fit$draws("gm[8]")) %>% .$`gm[8]`),prior = rnorm(4000,0,1))
    
    Bayesfactor_data = data.frame(variable = c("sigmam_beta","metabias_beta"),BF = c(bf_sigmam,bf_metabias), subs = subs)

  }
  
  groupmeans = fit$summary("gm") %>% 
    mutate(variable = c("beta","sigma_e","sigma_k","sigma_m","meta_bias","conf_prec","sigmam_beta","metabias_beta"),
           subs = subs) %>% mutate(type = type)

  groupmeans = full_join(groupmeans,Bayesfactor_data)
  
  df = rbind(df,groupmeans)  
  
}


dq = data.frame(means = rep(rep(0,5),each = 2), 
           sd = rep(c(1,0.5,0.25,0.05,0.01),each = 2), 
           type = rep(c("wide","reference","narrow","super_narrow","extremely_narrow"),each = 2),
           variable = rep(c("sigmam_beta","metabias_beta")),
           subs = rep(0,5*2))


draws <- dq  %>% 
  rowwise() %>% 
  mutate(draws = list(rnorm(4000, means, sd))) %>% 
  unnest(draws)

# stan-like summary
summary_df <- draws %>% 
  group_by(variable, subs,type) %>% 
  summarise(
    mean = mean(draws),
    q5 = hdi(draws, .width = 0.90)[1],
    q95 = hdi(draws, .width = 0.90)[2],
    .groups = "drop"
  )

summary_df

summary_df$type = factor(
  summary_df$type,
  levels = c("wide", "reference", "narrow", "super_narrow","extremely_narrow")
)

pp2 = summary_df %>% filter(variable == "sigmam_beta") %>% 
    rename(Prior = type) %>% 
  ggplot(aes(x = as.numeric(subs), y = mean, ymin = q5, ymax = q95))+
  geom_pointrange(aes(fill = Prior),col = "black",shape = 21, position = position_dodge(width = 0.1))+
  theme_classic(base_size = 14)+
  scale_y_continuous(breaks = c(-2.0, -1.5, -1.0, -0.5, -0.15, 0.15,  0.5,  1.0,  1.5,  2.0),
                     labels = c(-2.0, -1.5, -1.0, -0.5, -0.15, 0.15,  0.5,  1.0,  1.5,  2.0))+
  coord_cartesian(ylim = c(-1.5,1.5))+
  scale_x_continuous(limits = c(-0.1,0.1))+
  geom_hline(yintercept = 0, linetype = 2)+
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.line.x = element_blank(),
        axis.line.y = element_line(linewidth = 1.1),
        legend.position = "none")+
  ylab("Mean 90%HDI")



df = df %>% 
  mutate(type2 = ifelse(type == "superduper_narrow","extremely_narrow",type)) %>% 
  mutate(type2 = ifelse(type2 == "standard","reference",type2))

df$type2 = factor(
  df$type2,
  levels = c("wide", "reference", "narrow", "super_narrow","extremely_narrow")
)
linewidth = 0.3
text = 2
# estimates = 
estimates = rbind(df %>% filter(variable %in% c("sigmam_beta","metabias_beta")) %>% 
        filter(variable == "sigmam_beta")%>% 
        select(variable,subs,type2,q5,q95,mean)) %>% 
  rename(Prior = type2) %>% 
  ggplot(aes(x = as.numeric(subs), y = mean, ymin = q5, ymax = q95))+
  geom_pointrange(aes(fill = Prior),position = position_dodge(width = 3), shape = 21, col = "black")+
  theme_classic(base_size = 14)+
  
  scale_x_continuous(limits = c(-2,52), breaks = c(0, 15,20,25,30,35,40,45,50), labels = c(0, 15,20,25,30,35,40,45,50))+
  scale_y_continuous(breaks = seq(-0.1,0.1,by = 0.05))+
  coord_cartesian(ylim = c(-0.153,0.15))+
  geom_hline(yintercept = 0, linetype = 2)+
  geom_segment(aes(x = 12, xend = 12, y = -0.16, yend = 0.16), col = "black",linewidth = 1.1)+
  geom_segment(aes(x = 12-linewidth, xend = 12, y = -0.15, yend = -0.15), col = "black",linewidth = 0.8)+
  geom_segment(aes(x = 12-linewidth, xend = 12, y = -0.1, yend = -0.1), col = "black",linewidth = 0.8)+
  geom_segment(aes(x = 12-linewidth, xend = 12, y = -0.05, yend = -0.05), col = "black",linewidth = 0.8)+
  # geom_segment(aes(x = 10-linewidth, xend = 10, y = 0, yend = 0), col = "black",linewidth = 0.9)+
  geom_segment(aes(x = 12-linewidth, xend = 12, y = 0.05, yend = 0.05), col = "black",linewidth = 0.8)+
  geom_segment(aes(x = 12-linewidth, xend = 12, y = 0.1, yend = 0.1), col = "black",linewidth = 0.8)+
  geom_segment(aes(x = 12-linewidth, xend = 12, y = 0.15, yend = 0.15), col = "black",linewidth = 0.8)+
  
  geom_label(aes(x = 12-linewidth-text, y = -0.15, label = "-0.15"), col = "black",  linewidth = 0, size = 4.1)+
  geom_label(aes(x = 12-linewidth-text, y = -0.1, label = "-0.10"), col = "black",  linewidth = 0, size = 4.1)+
  geom_label(aes(x = 12-linewidth-text, y = -0.05, label = "-0.05"), col = "black",  linewidth = 0, size = 4.1)+
  geom_label(aes(x = 12-linewidth-text, y =  0.05, label = "0.05"), col = "black",  linewidth = 0, size = 4.1)+
  geom_label(aes(x = 12-linewidth-text, y = 0.1, label = "0.10"), col = "black",  linewidth = 0, size = 4.1)+
  geom_label(aes(x = 12-linewidth-text, y = 0.15, label = "0.15"), col = "black",  linewidth = 0, size = 4.1)+
  # facet_wrap(~variable)+
    theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        axis.line.y = element_blank(),
        legend.position = "top")+
  labs(x = "N Subjects")+
  labs(x = "")
  


p2 = (estimates + inset_element(pp2, left = 0, bottom = 0.01, right = 0.2, top = 1))

p2
ggsave(here::here("Sequential sampling" , "figures","estimates_v2.png"),combined_estimates, dpi = 300, width = 14, height = 10)
```


```{r,fig.height=8.4, fig.width=15}
pq = rbind(df %>% filter(variable %in% c("sigmam_beta","metabias_beta")) %>% 
        filter(variable == "sigmam_beta")%>% 
        select(variable,subs,type2,q5,q95,mean,BF)) %>% 
  rename(Prior = type2) %>% 
    group_by(Prior, variable) %>%
  group_modify(~ add_row(.x, subs = "0", BF = 1)) %>%
  ungroup() %>% 
  ggplot(aes(x = as.numeric(subs), y = log(BF)))+
  geom_line(aes(col = Prior,
              linetype = ifelse(Prior == "reference", "dashed","solid")))+
  geom_pointrange(aes(fill = Prior, ymin = log(BF), ymax = log(BF)),shape = 21, col = "black")+
  theme_classic(base_size = 14)+
   labs(y = "Log(Bayes Factor)", x = "N subjects")+
  geom_hline(yintercept = c(log(1/30),log(30)), linetype = 2)+
  scale_y_continuous(breaks = c(round(log(1/30),2),0,round(log(30),2)))+
  scale_x_continuous(limits = c(-2,52), breaks = c(0, 15,20,25,30,35,40,45,50), labels = c(0, 15,20,25,30,35,40,45,50))+
  # facet_wrap(~variable)+
  theme(legend.position = "none")


fullplot = p2/ pq

fullplot

ggsave(here::here("Sequential sampling" , "figures","Bayesfactors_v2_both.tiff"),fullplot, dpi = 300, width = 37.56, height = 21.04, units = "cm")

ggsave(here::here("Sequential sampling" , "figures","Bayesfactors_v2_p1.tiff"),p2, dpi = 300, width = 37.56, height = 21.04/3, units = "cm")
ggsave(here::here("Sequential sampling" , "figures","Bayesfactors_v2_p2.tiff"),pq, dpi = 300, width = 37.56, height = 21.04/2, units = "cm")

```
