---
title: "Run_model"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(cmdstanr, tidyverse,posterior, bayesplot, tidybayes,
               brms, patchwork, cowplot,ggpubr,flextable)


invisible(lapply(
  list.files(here::here("Experimental analysis", "Scripts"), full.names = TRUE),
  function(f) source(f, echo = FALSE, print.eval = FALSE)
))

```
## Extracting the data:

```{r, warning=F, message=F}
df = load_data()

dd = df %>% 
  mutate(subject = as.numeric(as.factor(subject))) %>% 
  filter(ID != "Rasmus_2026_04_02") %>% 
  filter(Trialtype == "Main", scale == "conf") %>% drop_na() 

```



## plotting the behavioral data:
```{r, fig.height=6,fig.width=8, message=F,warning=F}
plot_beh_data(df,NULL,F)

plot_beh_data_tog(df %>% filter(Trialtype == "Main"), NULL, F)

plot_beh_data_tog(df %>% mutate(subject = as.numeric(as.factor(subject))) %>% 
  filter(subject %in% 1:11) %>% 
  filter(Trialtype == "Main", scale == "conf") %>% drop_na(), 6, F)
```

## fit the standard model with meta-uncertainty and meta-bias
```{r}
model = cmdstanr::cmdstan_model(here::here("Stanmodels","Heurestic models","Emperical dataanalysis","hierarchical","Full_Heurestic.stan"))


model = cmdstanr::cmdstan_model(here::here("Stanmodels","Heurestic models","Emperical dataanalysis","hierarchical","Full_Heurestic_omega.stan"))
model = cmdstanr::cmdstan_model(here::here("Stanmodels","Heurestic models","Emperical dataanalysis","hierarchical","Full_heurestic_x1.stan"),
                                cpp_options = list(stan_threads = TRUE))

# model = cmdstanr::cmdstan_model(here::here("Stanmodels","Heurestic models","Emperical dataanalysis","hierarchical","vectorized.stan"))


datastan = list(N = nrow(dd),
                S = length(unique(dd$ID)),
                S_id = as.numeric(as.factor(dd$ID)),
                a = dd$Y,
                a_vec = dd$Y,
                RT = dd$RT,
                D = dd$D,
                C = dd$Confidence,
                X = dd$X * dd$D,
                XD = dd$X,
                minRT = min(dd$RT),
                ACC = dd$Correct,
                interval = dd$interval)

pf = model$pathfinder(data = datastan, num_threads = 4, psis_resample = F, calculate_lp = F)


fit <-model$sample(
  data = datastan,
  refresh = 10,
  iter_sampling = 500,
  iter_warmup = 500,
  adapt_delta = 0.95,
  max_treedepth = 12,
  init  = pf,
  parallel_chains = 4)
 

fit$save_object(here::here("Experimental analysis","Heurestic models","saved models","saved models hier",paste0("fit_finalheu_lapse_cypertron.rds")))

```


```{r}
fit_hier <- readRDS(here::here("Experimental analysis","Heurestic models","saved models","saved models hier","fit_finalheu_lapse.rds"))
```


```{r, fig.width=16,fig.height=12}
dia_hier(fit_hier, dd)
```



# posterior predictives:

```{r, fig.width=8,fig.height=6, error=F,message=F,warning=F}
pps = pp_hier(fit_hier, dd, n_bins = 10)

pps[[1]]
```


```{r, fig.width=8,fig.height=6, error=F,message=F,warning=F}
pps[[2]]
```


```{r,fig.height=12, fig.width=18}
library(ggplot2)
library(patchwork)

# Arrange in a 2-row × 4-column grid, collect all legends
combined_plot <- wrap_plots(pps[[2]], ncol = 4, nrow = 2, guides = "collect", axis_titles = "collect")

combined_plot = combined_plot+theme(axis.title = element_text(size = 14),
                       axis.text = element_text(size = 12, color = "black"),
                       axis.ticks.length = unit(0.2, "cm"))


combined_plot


ggsave(here::here("Preregistration","Figures","Pilot_predictive_checks.PNG"),dpi = 300, height = 12, width = 18)

```


```{r,fig.height=8,fig.width=8}
correlations = correlation_matrix(fit_hier)

correlations
```


```{r, fig.width=12,fig.height=8}
get_marginal_estimates(fit_hier)
```




