---
title: "Run_model"
output:
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(cmdstanr, tidyverse,posterior, bayesplot, tidybayes,
               brms, patchwork, cowplot,ggpubr,flextable)


invisible(lapply(
  list.files(here::here("Experimental analysis", "Scripts"), full.names = TRUE),
  function(f) source(f, echo = FALSE, print.eval = FALSE)
))

```
## Extracting the data:

```{r, warning=F, message=F}
df = load_data()
```



## plotting the behavioral data:
```{r, fig.height=6,fig.width=8, message=F,warning=F}
plot_beh_data(df %>%   
                filter(Trialtype == "Main", scale == "conf") %>% 
                mutate(subject = as.numeric(as.factor(ID))) %>% drop_na(),
              5,
              F)


plot_beh_data(df %>% filter(ID == "Rasmus_2026_04_02" & Trialtype == "Main"),NULL,F)

```

## fit the standard model with meta-uncertainty and meta-bias
```{r}
model1 = cmdstanr::cmdstan_model(here::here("Stanmodels","Heurestic models","Emperical dataanalysis","Single Subject","Heurestic.stan"))
model1 = cmdstanr::cmdstan_model(here::here("Stanmodels","Heurestic models","Emperical dataanalysis","Single Subject","Heurestic_v2.stan"))
model1 = cmdstanr::cmdstan_model(here::here("Stanmodels","Heurestic models","Emperical dataanalysis","Single Subject","heu_xx.stan"))

dd = df %>% 
  mutate(subject = as.numeric(as.factor(subject))) %>% 
  filter(Trialtype == "Main", scale == "conf") %>% drop_na()

dd_by_subj <- split(dd, dd$ID)

fits <- lapply(dd_by_subj, function(d) {
  fit_model_ss(d, model1, 500)
})
```


```{r}
models = list.files(here::here("Experimental analysis","Heurestic models","saved models","single subject","x1"), full.names = T)

fits = list()
for(model in models[1:9]){
  fit = readRDS(model)
  fits[[str_remove(str_remove(str_split(model, "/")[[1]][10],".rds"),"fit_")]] = fit  
}

models = list.files(here::here("Experimental analysis","Heurestic models","saved models","single subject","x"), full.names = T)

fits2 = list()
for(model in models[1:9]){
  fit = readRDS(model)
  fits2[[str_remove(str_remove(str_split(model, "/")[[1]][10],".rds"),"fit_")]] = fit  
}


q = q+1
name = names(fits)[q]
name

loo::loo_compare(
  list(
    oldx = fits2[[name]]$loo(),
    newx = fits[[name]]$loo()
  )
)

```


```{r, fig.width=8,fig.height=6}
dia(fits, dd)
```



# posterior predictives:

```{r, fig.width=8,fig.height=6, error=F,message=F,warning=F}
pp(fits, dd, n_bins = 10)
```




