---
title: "Decision and Confidence: Evidence-Based Policy with Metacognition"
author: ""
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: 
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
    number_sections: true
    theme: flatly
    highlight: tango
    code_folding: hide
    df_print: paged
---


```{r}
pacman::p_load(cmdstanr, tidyverse,posterior, bayesplot, tidybayes,
               brms, patchwork, cowplot,ggpubr,flextable)


invisible(lapply(
  list.files(here::here("Analysis", "Scripts"), full.names = TRUE),
  function(f) source(f, echo = FALSE, print.eval = FALSE)
))


df <- read_csv(here::here("Data","Pilots","Kelly_2025_17_12","RDM_reportz_sub3_1.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
  # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  filter(RT < 2.5) %>% 
  mutate(Confidence = (SR_conf+1)/2)


mod = cmdstanr::cmdstan_model(here::here("Derivations","test_nort.stan"))


datastan = list(a = df$Y,
                RT = df$RT,
                D = df$D,
                C = df$Confidence,
                N = nrow(df),
                X = df$coherence)


fit_kelly = mod$sample(data = datastan,
                 iter_warmup = 2000,
                 refresh = 100,
                 adapt_delta = 0.90,
                 iter_sampling = 2000,
           parallel_chains = 4)

fit_kelly$save_object(here::here("Savedmodels","removed_models","fit1_kelly_nort_mec.rds"))


df <- read_csv(here::here("Data","Pilots","Jesper_2025_17_12","RDM_reportz_sub5.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2)

# df$RT[1] = df$RT[1]-0.5



datastan = list(a = df$Y,
                RT = df$RT,
                D = df$D,
                C = df$Confidence,
                N = nrow(df),
                X = df$coherence)


fit_jesper = mod$sample(data = datastan,
                 iter_warmup = 2000,
                 refresh = 100,
                 
                 adapt_delta = 0.90,
                 iter_sampling = 2000,
           parallel_chains = 4)



fit_jesper$save_object(here::here("Savedmodels","removed_models","fit1_jespere_nort_mec.rds"))





df <- read_csv(here::here("Data","Pilots","Siebe_2025_03_12","data.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2) %>% 
  filter(RT < 2.5) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  drop_na()


# mod = cmdstanr::cmdstan_model(here::here("Derivations","test_conf.stan"))

datastan = list(a = df$Y,
                RT = df$RT,
                D = df$D,
                C = df$Confidence,
                N = nrow(df),
                X = df$coherence)


fit_siebe = mod$sample(data = datastan,
                 iter_warmup = 2000,
                 refresh = 100,
                 
                 adapt_delta = 0.90,
                 iter_sampling = 2000,
           parallel_chains = 4)



fit_siebe$save_object(here::here("Savedmodels","removed_models","fit1_siebe_nort_mec.rds"))



df <- read_csv(here::here("Data","Pilots","Siebe_2025_17_12","RDM_reportz_sub6.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2)  %>% 
  filter(RT < 2.5) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  drop_na()




# mod = cmdstanr::cmdstan_model(here::here("Derivations","test_conf.stan"))

datastan = list(a = df$Y,
                RT = df$RT,
                D = df$D,
                C = df$Confidence,
                N = nrow(df),
                X = df$coherence)


fit_siebe2 = mod$sample(data = datastan,
                 iter_warmup = 2000,
                 refresh = 100,
                 
                 adapt_delta = 0.90,
                 iter_sampling = 2000,
           parallel_chains = 4)

fit_siebe2$save_object(here::here("Savedmodels","removed_models","fit1_fit_siebe2_nort_mec.rds"))


```


```{r, fig.width=8,fig.height=6}
dia = function(fit){
  
  parameters = c("sigma_choice","mean_choice","prec_conf","sigma_m","sigma_e")
  sum = fit$summary(c(parameters))

  plot = mcmc_pairs(fit$draws(c(parameters)),np = nuts_params(fit))
  plot2 = mcmc_trace(fit$draws(c(parameters)),np = nuts_params(fit))
  
  return(list(sum,plot,plot2, fit$diagnostic_summary()))
  
}

dia(fit_kelly)


```


```{r, fig.width=8,fig.height=6}
dia(fit_jesper)
```


```{r, fig.width=8,fig.height=6}
dia(fit_siebe)
```



```{r, fig.width=8,fig.height=6}
dia(fit_siebe2)
```

```{r}
df <- read_csv(here::here("Data","Pilots","Kelly_2025_17_12","RDM_reportz_sub3_1.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
  filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  filter(RT < 2.5) %>% 
  mutate(Confidence = (SR_conf+1)/2)





df <- read_csv(here::here("Data","Pilots","Siebe_2025_03_12","data.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>%
  filter(Trialtype == "Main") %>%
  # filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2) %>%
  filter(RT < 2.5) %>%
  dplyr::select(Y,RT,D,Confidence,coherence,X,ACC) %>%
  drop_na()




fit = fit_siebe
# preds = data.frame(fit$summary("pred_rt"))
# 
# df %>%
#   mutate(preds_mean = preds$mean,
#          preds_q95 = preds$q95,
#          preds_q5 = preds$q5) %>%
#   ggplot()+
#   geom_point(aes(x = X, y = RT))+
#     geom_pointrange(aes(x = X, y = preds_mean, ymin = preds_q5, ymax = preds_q95), col = "red")

# 
# 
# df %>% 
#   mutate(preds_mean = preds$mean,
#          preds_q95 = preds$q95,
#          preds_q5 = preds$q5) %>% 
#   ggplot()+
#   # geom_point(aes(x = X, y = RT))+
#     geom_pointrange(aes(x = RT, y = preds_mean, ymin = preds_q5, ymax = preds_q95))
#     
#     
preds = data.frame(fit$summary("mu_conf"))

    

df %>% 
  mutate(preds_mean = preds$mean,
         preds_q95 = preds$q95,
         preds_q5 = preds$q5) %>% 
  ggplot()+
  geom_point(aes(x = X, y = Confidence, col = as.factor(ACC)))+
    geom_pointrange(aes(x = X, y = preds_mean, ymin = preds_q5, ymax = preds_q95, col = as.factor(ACC)))
    


df %>% 
  mutate(preds_mean = preds$mean,
         preds_q95 = preds$q95,
         preds_q5 = preds$q5) %>% 
  ggplot()+
    geom_pointrange(aes(x = Confidence, y = preds_mean, ymin = preds_q5, ymax = preds_q95, col = as.factor(ACC)))+
  geom_abline()
    
    
    
    


```


```{r}

df <- read_csv(here::here("Data","Pilots","Kelly_2025_17_12","RDM_reportz_sub3_1.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
  # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  filter(RT < 2.5) %>% 
  mutate(Confidence = (SR_conf+1)/2)




fit = fit_kelly
# preds = data.frame(fit$summary("pred_rt"))
# 
# df %>% 
#   mutate(preds_mean = preds$mean,
#          preds_q95 = preds$q95,
#          preds_q5 = preds$q5) %>% 
#   ggplot()+
#   geom_point(aes(x = X, y = RT))+
#     geom_pointrange(aes(x = X, y = preds_mean, ymin = preds_q5, ymax = preds_q95), col = "red")
#     


# df %>% 
#   mutate(preds_mean = preds$mean,
#          preds_q95 = preds$q95,
#          preds_q5 = preds$q5) %>% 
#   ggplot()+
#   # geom_point(aes(x = X, y = RT))+
#     geom_pointrange(aes(x = RT, y = preds_mean, ymin = preds_q5, ymax = preds_q95))
#     
    
preds = data.frame(fit$summary("mu_conf"))

    

df %>% 
  mutate(preds_mean = preds$mean,
         preds_q95 = preds$q95,
         preds_q5 = preds$q5) %>% 
  ggplot()+
  geom_point(aes(x = X, y = Confidence, col = as.factor(ACC)))+
    geom_pointrange(aes(x = X, y = preds_mean, ymin = preds_q5, ymax = preds_q95, col = as.factor(ACC)))
    
    
df %>% 
  mutate(preds_mean = preds$mean,
         preds_q95 = preds$q95,
         preds_q5 = preds$q5) %>% 
  ggplot()+
    geom_pointrange(aes(x = Confidence, y = preds_mean, ymin = preds_q5, ymax = preds_q95, col = as.factor(ACC)))+
  geom_abline()
    
 

```



```{r}

cols_10 <- c(
  "darkred",  # very dark red
  "darkgreen",  # very dark green
  "#ef3b2c",  # dark red
  "#41ab5d",  # dark green
  "red",  # darker red
  "green",  # green
  "#ef3b2c",  # dark red
  "#41ab5d",  # dark green
  "darkred",  # very dark red
  "darkgreen"   # very dark green
)

df <- read_csv(here::here("Data","Pilots","Jesper_2025_17_12","RDM_reportz_sub5.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2)


evi = fit_jesper$summary("evidence")
ehat = fit_jesper$summary("ehat")



data.frame(evidence = evi$mean, ehat = ehat$mean, conf = df$Confidence, correct = as.factor(df$ACC)) %>% 
    mutate(conf = as.factor(cut(conf,5))) %>%
  ggplot(aes(x = evidence, y = ehat, fill = interaction(correct,conf)),col = correct)+geom_point(shape = 21, size = 3)+
  scale_fill_manual(values = cols_10)+
  scale_color_manual(values = c("red","green"))
  facet_wrap(~correct)

data.frame(evidence = evi$mean, ehat = ehat$mean, conf = df$Confidence, correct = as.factor(df$ACC)) %>% 
  mutate(dif = evidence-ehat) %>% 
  ggplot(aes(x = dif, y = conf, col = correct))+geom_point()
  facet_wrap(~correct)


```

```{r}


df <- read_csv(here::here("Data","Pilots","Siebe_2025_03_12","data.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>%
  filter(Trialtype == "Main") %>%
  # filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2) %>%
  filter(RT < 2.5) %>%
  dplyr::select(Y,RT,D,Confidence,coherence,X,ACC) %>%
  drop_na()



evi = fit_siebe$summary("evidence")
ehat = fit_siebe$summary("ehat")



data.frame(evidence = evi$mean, ehat = ehat$mean, conf = df$Confidence, correct = as.factor(df$ACC)) %>% 
    mutate(conf = as.factor(cut(conf,5))) %>%
  ggplot(aes(x = evidence, y = ehat, fill = interaction(correct,conf)),col = correct)+geom_point(shape = 21, size = 3)+
  scale_fill_manual(values = cols_10)+
  scale_color_manual(values = c("red","green"))
  facet_wrap(~correct)
  
  
data.frame(evidence = evi$mean, ehat = ehat$mean, conf = df$Confidence, correct = as.factor(df$ACC)) %>% 
  mutate(dif = evidence-ehat) %>% 
  ggplot(aes(x = dif, y = conf, col = correct))+geom_point()
  facet_wrap(~correct)

```




```{r}


df <- read_csv(here::here("Data","Pilots","Kelly_2025_17_12","RDM_reportz_sub3_1.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
  # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  filter(RT < 2.5) %>% 
  mutate(Confidence = (SR_conf+1)/2)


evi = fit_kelly$summary("evidence")
ehat = fit_kelly$summary("ehat")




data.frame(evidence = evi$mean, ehat = ehat$mean, conf = df$Confidence, correct = as.factor(df$ACC)) %>% 
    mutate(conf = as.factor(cut(conf,5))) %>%
  ggplot(aes(x = evidence, y = ehat, fill = interaction(correct,conf)),col = correct)+geom_point(shape = 21, size = 3)+
  scale_fill_manual(values = cols_10)+
  scale_color_manual(values = c("red","green"))
  facet_wrap(~correct)
data.frame(evidence = evi$mean, ehat = ehat$mean, conf = df$Confidence, correct = as.factor(df$ACC)) %>% 
  mutate(dif = evidence-ehat) %>% 
  ggplot(aes(x = dif, y = conf, col = correct))+geom_point()
  facet_wrap(~correct)

```


## fit hierarchical version

```{r}
df4 <- read_csv(here::here("Data","Pilots","Kelly_2025_17_12","RDM_reportz_sub3_1.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
  # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  filter(RT < 2.5) %>% 
  mutate(Confidence = (SR_conf+1)/2) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  mutate(Subject = 4)



df3 <- read_csv(here::here("Data","Pilots","Jesper_2025_17_12","RDM_reportz_sub5.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
    mutate(Confidence = (SR_conf+1)/2) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  mutate(Subject = 3) 


df2 <- read_csv(here::here("Data","Pilots","Siebe_2025_03_12","data.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2) %>% 
  filter(RT < 2.5) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  mutate(Subject = 2) %>% 
  drop_na()


df1 <- read_csv(here::here("Data","Pilots","Siebe_2025_17_12","RDM_reportz_sub6.csv")) %>%
  mutate(resp = ifelse(resp == "down",0,1),
         interval = as.numeric(interval),
       stim = ifelse(`dots direction` == 270, -coherence,coherence)) %>%
  mutate(ACC = ifelse(resp == 1 & stim > 0, 1,
                      ifelse(resp == 0 & stim < 0, 1,0))) %>%
    mutate(D = ifelse(`dots direction` == 270, -1, 1)) %>% 
  filter(Trialtype == "Main") %>%
  filter(SR_conf != "None") %>%
    # filter(scale == "conf") %>%
  mutate(SR_conf = as.numeric(SR_conf)) %>%
  rename(X = stim, RT = RTdec, Correct = cor, Y = resp) %>%
  mutate(Confidence = (SR_conf+1)/2)  %>% 
  filter(RT < 2.5) %>% 
  dplyr::select(Y,RT,D,Confidence,coherence,RTrating,X) %>% 
  mutate(Subject = 1) %>% 
  drop_na()


dd = rbind(df1,df2,df3,df4)


mod = cmdstanr::cmdstan_model(here::here("Derivations","Hierarchical","nort.stan"))


datastan = list(a = dd$Y,
                D = dd$D,
                C = dd$Confidence,
                N = nrow(dd),
                X = dd$coherence,
                S = length(unique(dd$Subject)),
                S_id = dd$Subject)


fit = mod$sample(data = datastan,
                 iter_warmup = 500,
                 refresh = 100,
                 adapt_delta = 0.90,
                 max_treedepth = 12,
                 iter_sampling = 500,
           parallel_chains = 4)

fit$save_object(here::here("Savedmodels","removed_models","fit1_hier_mec.rds"))


parameters = c("gm","tau_u")
sum = fit$summary(c(parameters))

plot = mcmc_pairs(fit$draws(c(parameters)),np = nuts_params(fit))
plot2 = mcmc_trace(fit$draws(c(parameters)),np = nuts_params(fit))
```



```{r, fig.width=14,fig.height=12}
sum
plot
plot2
```


```{r, fig.width=8,fig.height=6}

parameters = c("gm[1]","tau_u[1]","mean_choice[1]","mean_choice[2]","mean_choice[3]","mean_choice[4]")
sum = fit$summary(c(parameters))

plot = mcmc_pairs(fit$draws(c(parameters)),np = nuts_params(fit),
  transformations = list(
    `tau_u[1]` = exp
  ))
plot2 = mcmc_trace(fit$draws(c(parameters)),np = nuts_params(fit),
  transformations = list(
    `tau_u[1]` = exp
  ))

sum
plot
plot2

```


```{r, fig.width=8,fig.height=6}

parameters = c("gm[2]","tau_u[2]","sigma_choice_log[1]","sigma_choice_log[2]","sigma_choice_log[3]","sigma_choice_log[4]")
sum = fit$summary(c(parameters))

plot = mcmc_pairs(fit$draws(c(parameters)),np = nuts_params(fit),transformations = list(
    `tau_u[2]` = log
    
  ))
plot2 = mcmc_trace(fit$draws(c(parameters)),np = nuts_params(fit),transformations = list(
    `tau_u[2]` = log
    
  ))

sum
plot
plot2

```



```{r, fig.width=8,fig.height=6}

parameters = c("gm[3]","tau_u[3]","sigma_m_log[1]","sigma_m_log[2]","sigma_m_log[3]","sigma_m_log[4]")
sum = fit$summary(c(parameters))

plot = mcmc_pairs(fit$draws(c(parameters)),np = nuts_params(fit),
  transformations = list(
    `tau_u[3]` = log
  ))
plot2 = mcmc_trace(fit$draws(c(parameters)),np = nuts_params(fit),
  transformations = list(
    `tau_u[3]` = log
  ))

sum
plot
plot2

```




```{r, fig.width=8,fig.height=6}

parameters = c("gm[4]","tau_u[4]","prec_conf_log[1]","prec_conf_log[2]","prec_conf_log[3]","prec_conf_log[4]")
sum = fit$summary(c(parameters))

plot = mcmc_pairs(fit$draws(c(parameters)),np = nuts_params(fit),
  transformations = list(
    `tau_u[4]` = log
  ))
plot2 = mcmc_trace(fit$draws(c(parameters)),np = nuts_params(fit),
  transformations = list(
    `tau_u[4]` = log
  ))

sum
plot
plot2

```




```{r, fig.width=8,fig.height=6}

parameters = c("gm[5]","tau_u[5]","sigma_e_log[1]","sigma_e_log[2]","sigma_e_log[3]","sigma_e_log[4]")
sum = fit$summary(c(parameters))

plot = mcmc_pairs(fit$draws(c(parameters)),np = nuts_params(fit),
  transformations = list(
    `tau_u[5]` = log
  ))
plot2 = mcmc_trace(fit$draws(c(parameters)),np = nuts_params(fit),
  transformations = list(
    `tau_u[5]` = log
  ))

sum
plot
plot2

```

## meta-d

```{r}
library(statConfR)


data = df4 %>% mutate(conf_bin = cut(Confidence,4),
                      stimulus  = as.factor(D),
                      participant = 1,
                      rating = as.numeric(as.factor(conf_bin)),
                      correct = ifelse(Y == 0 & D == -1,1,ifelse(Y == 1 & D== 1,1,0))) %>% drop_na()



q = fitMetaDprime(data)

q$Ratio

```

