---
title: "Derivation of Stochastic Posterior Criterion"
output: html_document
---

# 1. Latent evidence and posterior

Assume the true state of the world on a trial is \(D \in \{-1,+1\}\), and the agent observes a latent, noisy evidence of this \(e\), $\mu$ represents the signal strength i.e. coherence in a Random dot Motion task and has to be strictly positive as the sign comes from D.

We assume as Signal detection theory that the evidence is Gaussian:

$$
e \sim \mathcal{N}(D \cdot \mu, \sigma)
$$

The agent computes the posterior probability that the stimulus is $+1$ given $e$:

$$
P(D=1 \mid e) = \frac{P(e \mid D=1) \cdot P(D=1)}{P(e \mid D=1) \cdot P(D=1) + P(e \mid D=-1) \cdot P(D=-1)}
$$

I.e. the posterior probability that the state is 1 given the evidence is just the likelihood of the evidence given that the state was 1 weighted by the prior, divided by the total probability.

> where `P(D)` is the prior over the stimulus which must be `P(D = 1) = 1 - P(D = -1)` .

If we now assume that the prior is flat (`P(D)`). we have:

$$
P(D=1 \mid e) = \frac{P(e \mid D=1)}{P(e \mid D=1) + P(e \mid D=-1)}
$$

Plugging in the gaussian distributions from the assumption of the evidence:


$$
e \mid D=1 \sim \mathcal{N}(\mu, \sigma^2), \quad 
e \mid D=-1 \sim \mathcal{N}(-\mu, \sigma^2)
$$

Then the likelihoods are:

$$
P(e \mid D=1) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\Big(-\frac{(e - \mu)^2}{2\sigma^2}\Big), \quad
P(e \mid D=-1) = \frac{1}{\sqrt{2\pi\sigma^2}} \exp\Big(-\frac{(e + \mu)^2}{2\sigma^2}\Big)
$$

Plugging these into the posterior formula:


$$
\begin{aligned}
P(D=1 \mid e) &= \frac{\exp\Big(-\frac{(e - \mu)^2}{2\sigma^2}\Big)}{\exp\Big(-\frac{(e - \mu)^2}{2\sigma^2}\Big) + \exp\Big(-\frac{(e + \mu)^2}{2\sigma^2}\Big)}
\end{aligned}
$$

Now if one factors out the $\exp\Big(-\frac{(e - \mu)^2}{2\sigma^2}\Big)$ term from the numerator we get:

$$
P(D=1 \mid e) = \frac{1}{1 + \exp\Big(\frac{(e + \mu)^2 - (e - \mu)^2}{2\sigma^2}\Big)}
$$
writing out the sqaures $(e + \mu)^2 = e^2 + \mu^2 + 2\cdot e \cdot \mu$ & $(e - \mu)^2 = e^2 + \mu^2 - 2\cdot e \cdot \mu$, we end up with:

$$
P(D=1 \mid e) = \frac{1}{1 + \exp\Big(-\frac{2 \cdot e \cdot \mu}{\sigma^2}\Big)}
$$
This type of fraction is exactly the inverse logit transformation $g(.) = \frac{1}{1+exp(-x)}$, which means:
$$
P(D=1 \mid e) = g\Big(\frac{2 \cdot e \cdot \mu}{\sigma^2}\Big)
$$
From this one can get to the usual optimal policy of responding 1 when the probability of the true state of the world given the evidence is above 0.5 and otherwise respond -1, i.e.


# Decision Policy

## 1. on the probability scale:

From this posterior, the **optimal policy** under 0-1 loss is:

$$
a =
\begin{cases}
1 & \text{if } P(D=1 \mid e) > 0.5 \\
-1 & \text{otherwise}
\end{cases}
$$

Equivalently, since the sigmoid crosses 0.5 at 0, i.e. $g(0) = 0.5$, the only thing in the function that changes the sign is the evidence we get:

$$
a =
\begin{cases}
1 & \text{if } \frac{2 e \mu}{\sigma^2} > 0 \\
-1 & \text{if } \frac{2 e \mu}{\sigma^2} \le 0
\end{cases}
\quad \Longleftrightarrow \quad
a = 
\begin{cases}
1 & \text{if } e > 0 \\
-1 & \text{if } e \le 0
\end{cases}
$$

What this parameterization does allow is to say that the decision criterion (policy) is not on the latent evidence scale but on the probability scale. so we might introduce a different non-strict policy on the probability scale. given that the citerion needs to be bounded on $[0 , 1]$ the maximum entropy distribution must be the beta distribution:

$$
c \sim \text{Beta}(\alpha, \beta)
$$

So the idea is that on each trial a new citerion, c, is drawn (This is because the agent does not deterministically respond 1 or 0 given a particular probability of the true state of the world, thus this introduces "decision noise", which is placed on the posterior probability instead of on the stimulus axis.

$$
a =
\begin{cases}
1 & \text{if } P(D=1 \mid e) > c \\
-1 & \text{otherwise}
\end{cases}
$$

$$
a =
\begin{cases}
1 & \text{if } c < P(D=1 \mid e)\\
-1 & \text{otherwise}
\end{cases}
$$

This can then be written as:

$$
P(a = 1 | e) =  P(c < P(D=1 \mid e))
$$
as the probability distribution of c was given by $c \sim \text{Beta}(\alpha, \beta)$ this amounts to the cumulative beta distribution:

$$
P(a = 1 | e) =  P(c < P(D=1 \mid e)) = F_{beta}(P(D=1 \mid e) ; \alpha, \beta)
$$
which given what we found for $P(D = 1|e)$ becomes:

$$
P(a = 1 | e) =  P(c < P(D=1 \mid e)) = F_{beta}\Big(g\Big(\frac{2 \cdot e \cdot D}{\sigma^2}\Big) ; \alpha, \beta\Big)
$$

If this then is parameterized as a mean and precision beta distribution one can think of $\alpha$ as the decision bias with 0.5 being no bias (optimal policy) and $\beta$ being the precision of decision noise.




---

## 2. Stochastic Criterion on the Evidence Scale

Alternatively, place decision noise **directly on the evidence**:

$$
k \sim \mathcal{N}(\mu_k, \sigma_k^2)
$$

Decision policy:

$$
a =
\begin{cases}
1 & \text{if } e > k \\
-1 & \text{otherwise}
\end{cases}
$$

Then the probability of choosing 1 is:


$$
P(a = 1 \mid e) = P(k < e)
$$

Since k follows a normal distribution: $(k \sim \mathcal{N}(\mu_k, \sigma_k^2)$, we can calculate the above probability statement as:

$$
P(a = 1 \mid e) = \Phi\!\left(\frac{e - \mu_k}{\sigma_k}\right)
$$

where $\Phi(\cdot)$ denotes the standard normal cumulative distribution function.


# Response times

## 1. Absolute evidence

Now this decision does not come in a vacuum, but is accompanied by a response time (RT). This RT we assume is a function of the evidence, in such a way that stronger evidence will give faster responses i.e. easier trials will be faster. Further we posit that RT will have a lower bound that will be governed by a non-decision-time $RT_{ndt}$. This gives us that:
$$
RT \sim RT_{ndt} + f(|e|)
$$
here stronger evidence is given by the absolute value of the evidence. We might then also assume that the noise is log normally distributed in order to also withhold that RT's are strictly positive:
$$
RT \sim log(\mathcal{N}(RT_{ndt} + f(|e|), RT_\sigma)
$$




